### ISSUE TITLE
ImportError: cannot import name 'walk_files' from 'torchaudio.datasets.utils' 

### ISSUE THREAD

**Issue by Jee-King** [fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron#10]
Hi, thanks for your interesting work!

can you tell me the requirments that you used?  I train your work on cifar10-dvs with `torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1`, it generates an error as 

```
Namespace(T=20, T_max=64, alpha_learnable=False, batch_size=16, channels=128, dataset_name='CIFAR10DVS', detach_reset=True, device='cuda:6', init_tau=2.0, learning_rate=0.001, log_dir_prefix='./plif_test/logsd', max_epoch=1024, normalization='None', number_layer=4, split_by='number', use_max_pool=True, use_plif=True, val_ratio=0.15)
./plif_test/logsd/val_0.15_CIFAR10DVS_init_tau_2.0_use_plif_True_use_max_pool_True_T_20_c_128_n_4_split_by_number_normalization_None_detach_reset_True ./plif_test/logsd/pt_val_0.15_CIFAR10DVS_init_tau_2.0_use_plif_True_use_max_pool_True_T_20_c_128_n_4_split_by_number_normalization_None_detach_reset_True
Traceback (most recent call last):
  File "./codes/train_val.py", line 185, in <module>
    from spikingjelly.datasets.cifar10_dvs import CIFAR10DVS
  File "<frozen zipimport>", line 259, in load_module
  File "/opt/conda/envs/dual_learning/lib/python3.8/site-packages/spikingjelly-0.0.0.0.1-py3.8.egg/spikingjelly/datasets/__init__.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/opt/conda/envs/dual_learning/lib/python3.8/site-packages/spikingjelly-0.0.0.0.1-py3.8.egg/spikingjelly/datasets/speechcommands.py", line 7, in <module>
ImportError: cannot import name 'walk_files' from 'torchaudio.datasets.utils' (/opt/conda/envs/dual_learning/lib/python3.8/site-packages/torchaudio/datasets/utils.py)
```

**Comment by fangwei123456** [comment]
You can refer to this:
https://github.com/fangwei123456/spikingjelly/issues/52#issuecomment-802821080

You can solve this by:

https://github.com/fangwei123456/spikingjelly/commit/68026e10b37bd02e0276c1c07201a3ce7fdcd705

**Comment by Jee-King** [comment]
Thanks for your help! I will try it
